---
# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
#
include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Container-Scanning.gitlab-ci.yml

variables:
  CHOCO_PACKAGE_NAME: arq
  CHOCO_COMMUNITY_PUSH_URL: https://push.chocolatey.org/
  CHOCO_COMMUNITY_FEED: https://community.chocolatey.org/api/v2/

container_scanning:
  variables:
    DOCKER_IMAGE: chocolatey/choco:latest-linux
    CS_DISABLE_LANGUAGE_VULNERABILITY_SCAN: "false"

default:
  image: chocolatey/choco:latest-linux
  tags:
    - docker
    - real-time.com

stages:
  - build
  - test
  - push

build_job:
  stage: build
  script:
    - choco pack
  artifacts:
    paths:
      - /builds

test_job:
  stage: test
  script:
    - choco install -dv -s "'.;$CHOCO_COMMUNITY_FEED'" "$CHOCO_PACKAGE_NAME"
    - choco uninstall "$CHOCO_PACKAGE_NAME"
  artifacts:
    paths:
      - /builds

push_job:
  stage: push
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true
  script:
    - choco apikey --key $CHOCO_COMMUNITY_API_KEY --source $CHOCO_COMMUNITY_PUSH_URL
    - choco push --source $CHOCO_COMMUNITY_PUSH_URL
  artifacts:
    paths:
      - /builds
