---
name: Chocolatey Package

# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
on:    # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

env:
  CHOCO_PACKAGE_NAME: cura-new
  CHOCO_PUSH_URL: https://push.chocolatey.org/
  CHOCO_COMMUNITY_FEED: https://community.chocolatey.org/api/v2/

jobs:
  build:
    runs-on: windows-2016
    name: Build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      -
        name: Set key
        run: |
          choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source ${{ env.CHOCO_PUSH_URL }}
      -
        name: Install
        run: |
          choco install -dv --source ".;${{ env.CHOCO_COMMUNITY_FEED }}" ${{ env.CHOCO_PACKAGE_NAME }}
      -
        name: Push
        run: |
          choco push --api-key ${{ secrets.CHOCO_API_KEY }} --source ${{env.CHOCO_PUSH_URL }}
